version: "3.9"
services:
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./conf:/etc/nginx/conf.d/
    networks:
      - web
  app:
    build:
      context: .
      dockerfile: ./zipapp/Dockerfile
    volumes:
      - ./zipapp:/app
    networks:
      - web
  user:
    build:
      context: .
      dockerfile: ./userapp/Dockerfile
    volumes:
      - ./userapp:/app
    networks:
      - web
networks:
  web:
    driver: bridge
